### ISSUE TITLE
Open folder where file is converted

### ISSUE THREAD

**Issue by gustaveracosta** [ProjectCeleste/ProjectCeleste.GameFiles.Tools#20]
# Describe the feature

After converting the file to xml it would be nice to know exactly where it has gone with a button click. I keep on getting lost with this part.

## Is this feature related to a problem, describe

After convert files to xml I can't find the folder where it has been saved to

**Comment by martinmine** [comment]
This is a library - it has no UI. Not sure what you are trying to do or what you are expecting. I will close this since I think you are not in the right place. Let me know otherwise.
